# Contour Ingress example  
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
    kubernetes.io/ingress.class: contour
spec:
  rules:
  - http:
      paths:
      - path: /v2
        pathType: Prefix
        backend:
          service:
            name: web-v2
            port:
              name: http
      - path: /v1
        pathType: Prefix
        backend:
          service:
            name: web-v1
            port:
              name: http
