apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: guestbook
    tier: frontend
  name: frontend
  namespace: default
  resourceVersion: "2611"
spec:
  loadBalancerIP: 192.168.0.157
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  externalIPs:
  - 192.168.0.157
  selector:
    app: guestbook
    tier: frontend
  sessionAffinity: None
  type: LoadBalancer                                                                                                                                                     
